{% set name = "wagtail-grapple" %}
{% set version = "0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_grapple-{{ version }}.tar.gz
  sha256: cd2956d8bbd4e2b60a482829b00dbfbd782c6ca28ec5b0e50cd442b66a5e6898

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - wagtail >=4.1
    - graphene-django >=3,<4
    - wagtail-headless-preview

test:
  imports:
    - grapple
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/torchbox/wagtail-grapple
  summary: A Wagtail package that speeds up and simplifies implementing a GraphQL endpoint!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
