{% set name = "wagtail-grapple" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_grapple-{{ version }}.tar.gz
  sha256: 3f89a7ea98ed7fe1348ff10aeac503a510f6cde94cd6e667f738747db8432697

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=6.3
    - graphene-django >=3,<4
    - wagtail-headless-preview

test:
  imports:
    - grapple
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/torchbox/wagtail-grapple
  summary: A Wagtail package that speeds up and simplifies implementing a GraphQL endpoint!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
